Add inherited annotation on ResultRequiresPermission annotation so cl…
agorapulse/micronaut-permissions pull request #13
Opened 2023-07-26 07:08 UTC by Rigerwal

…asses inherited also trigger the interceptor

2023-07-26 08:17 UTC, musketyr requested changes
please, run `/gradlew licenseFormat` to fix the license violations

2023-07-26 11:07 UTC, DKarim approved these changes

2023-07-27 12:05 UTC, Rigerwal commented
Hi @musketyr , is it ok for you if I merge it ?

2023-07-27 12:06 UTC, musketyr approved these changes

2023-07-27 12:07 UTC, musketyr commented
> Hi @musketyr , is it ok for you if I merge it ?

sure @Rigerwal! feel free to merge and release.

2023-07-27 12:14 UTC, ludovic-faure-agora approved these changes

2023-07-27 12:18 UTC, merged